# Generated by Django 3.1.2 on 2020-11-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201110_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='course.episode'),
        ),
    ]
