# Generated by Django 3.1.2 on 2020-11-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201110_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepcontent',
            name='text',
            field=models.TextField(blank=True, help_text='This uses markdown format', null=True),
        ),
    ]
