# Generated by Django 3.1.2 on 2020-11-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_stepcontent_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepcontent',
            name='picture',
        ),
    ]
