# Generated by Django 3.1.2 on 2020-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20201110_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='text',
        ),
        migrations.AddField(
            model_name='step',
            name='content',
            field=models.TextField(default='This is some dummy content to place in existing steps `I believe it can fill some gaps` \n Love Joetib', help_text='This uses markdown format'),
            preserve_default=False,
        ),
    ]
