# Generated by Django 3.1.2 on 2020-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
